# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: panda_arm
  joint_model_group_pose: robot_ready
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - panda_1_joint1
    - panda_1_joint2
    - panda_1_joint3
    - panda_1_joint4
    - panda_1_joint5
    - panda_1_joint6
    - panda_1_joint7
    - panda_1_finger_joint1
    - panda_3_joint1
    - panda_3_joint2
    - panda_3_joint3
    - panda_3_joint4
    - panda_3_joint5
    - panda_3_joint6
    - panda_3_joint7
    - panda_3_finger_joint1
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: panda_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
  - name: panda_hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      panda_1_finger_joint1
  - name: panda_arm_2_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - panda_3_joint1
      - panda_3_joint2
      - panda_3_joint3
      - panda_3_joint4
      - panda_3_joint5
      - panda_3_joint6
      - panda_3_joint7
  - name: panda_hand_2_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      panda_3_finger_joint1
panda_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_1_joint1
    - panda_1_joint2
    - panda_1_joint3
    - panda_1_joint4
    - panda_1_joint5
    - panda_1_joint6
    - panda_1_joint7
  gains:
    panda_1_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_1_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_1_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_1_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_1_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_1_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_1_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
panda_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    panda_1_finger_joint1
  gains:
    panda_1_finger_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
panda_arm_2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_3_joint1
    - panda_3_joint2
    - panda_3_joint3
    - panda_3_joint4
    - panda_3_joint5
    - panda_3_joint6
    - panda_3_joint7
  gains:
    panda_3_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_3_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_3_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_3_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_3_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_3_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    panda_3_joint7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
panda_hand_2_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    panda_3_finger_joint1
  gains:
    panda_3_finger_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1