controller_list:
  - name: fake_panda_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
  - name: fake_panda_tool_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_1_finger_joint1
      - panda_1_finger_joint2
  - name: fake_panda_arm_2_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
  - name: fake_panda_tool_2_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_2_finger_joint1
      - panda_2_finger_joint2
initial:  # Define initial robot poses.
  - group: panda_arm
    pose: robot_ready
  - group: panda_tool
    pose: tool_open
  - group: panda_arm_2
    pose: robot_up_2
  - group: panda_tool_2
    pose: tool_close_2