controller_list:
  - name: fake_panda_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
  - name: fake_panda_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_1_finger_joint1
initial:  # Define initial robot poses.
  - group: panda_arm
    pose: robot_ready
  - group: panda_hand
    pose: tool_open