# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: robot_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: robot_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
robot_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  gains:
    panda_joint1:
      p: 12000
      d: 100
      i: 1
      i_clamp: 1
    panda_joint2:
      p: 18000
      d: 100
      i: 1
      i_clamp: 1
    panda_joint3:
      p: 12000
      d: 100
      i: 1
      i_clamp: 1
    panda_joint4:
      p: 12000
      d: 100
      i: 1
      i_clamp: 1
    panda_joint5:
      p: 10000
      d: 100
      i: 1
      i_clamp: 1
    panda_joint6:
      p: 7000
      d: 100
      i: 1
      i_clamp: 1
    panda_joint7:
      p: 7000
      d: 100
      i: 1
      i_clamp: 1
robot_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_finger_joint1
    - panda_finger_joint2
  gains:
    panda_finger_joint1:
      p: 1200
      d: 10
      i: 1
      i_clamp: 1
    panda_finger_joint2:
      p: 1200
      d: 10
      i: 1
      i_clamp: 1