controller_list:
  - name: fake_robot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: fake_robot_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
initial:  # Define initial robot poses per group
  - group: robot_arm
    pose: robot_up
  - group: robot_hand
    pose: tool_open